Repository drum-grammer/docker-pro, pull requests merged in 2024-05, with the labels that each got.

#8 [5월]변인정 / 나만의 도커이미지 제출
  contest/ururuwave/Dockerfile
  contest/ururuwave/myblog/.editorconfig
  contest/ururuwave/myblog/.gitattributes
  contest/ururuwave/myblog/.gitignore
  contest/ururuwave/myblog/404.html
  contest/ururuwave/myblog/LICENSE.txt
  contest/ururuwave/myblog/css/style.css
  contest/ururuwave/myblog/favicon.ico
  contest/ururuwave/myblog/icon.png
  contest/ururuwave/myblog/icon.svg
  contest/ururuwave/myblog/img/.gitkeep
  contest/ururuwave/myblog/img/myprofile.jpg
  contest/ururuwave/myblog/index.html
  contest/ururuwave/myblog/js/app.js
  contest/ururuwave/myblog/js/vendor/.gitkeep
  contest/ururuwave/myblog/package.json
  contest/ururuwave/myblog/robots.txt
  contest/ururuwave/myblog/site.webmanifest
  contest/ururuwave/myblog/webpack.common.js
  contest/ururuwave/myblog/webpack.config.dev.js
  contest/ururuwave/myblog/webpack.config.prod.js
Labels: 💿 나만의 도커 이미지 만들기

#17 [5월] 윤채림 / 찾아보면 좋은 키워드 : 도커파일, 도커 이미지 레이어 구조
  keyword/Rachel-3/cache-optimization.png
  keyword/Rachel-3/dockerfile-layers.png
  keyword/Rachel-3/optimized-dockerfile.png
  keyword/Rachel-3/윤채림.md
  mission/Rachel-3/Docker-screenshot.PNG
  mission/Rachel-3/Dockerfile
  mission/Rachel-3/mission.md
Labels: 찾아보면 좋은 키워드

#23 [5월] 김준영 - 나만의 도커 이미지 만들기
  contest/6-n0kim/dockerfile
  contest/6-n0kim/index.js
  mission/6-n0kim/docker screenshot.png
  mission/6-n0kim/dockerfile
  mission/6-n0kim/pre-mission.md
Labels: 💿 나만의 도커 이미지 만들기

#25 refactoring: 파일 정리
  contest/docker-images/6-n0kim/dockerfile
  contest/docker-images/6-n0kim/index.js
  contest/docker-images/ururuwave/Dockerfile
  contest/docker-images/ururuwave/myblog/.editorconfig
  contest/docker-images/ururuwave/myblog/.gitattributes
  contest/docker-images/ururuwave/myblog/.gitignore
  contest/docker-images/ururuwave/myblog/404.html
  contest/docker-images/ururuwave/myblog/LICENSE.txt
  contest/docker-images/ururuwave/myblog/css/style.css
  contest/docker-images/ururuwave/myblog/favicon.ico
  contest/docker-images/ururuwave/myblog/icon.png
  contest/docker-images/ururuwave/myblog/icon.svg
  contest/docker-images/ururuwave/myblog/img/.gitkeep
  contest/docker-images/ururuwave/myblog/img/myprofile.jpg
  contest/docker-images/ururuwave/myblog/index.html
  contest/docker-images/ururuwave/myblog/js/app.js
  contest/docker-images/ururuwave/myblog/js/vendor/.gitkeep
  contest/docker-images/ururuwave/myblog/package.json
  contest/docker-images/ururuwave/myblog/robots.txt
  contest/docker-images/ururuwave/myblog/site.webmanifest
  contest/docker-images/ururuwave/myblog/webpack.common.js
  contest/docker-images/ururuwave/myblog/webpack.config.dev.js
  contest/docker-images/ururuwave/myblog/webpack.config.prod.js
  lecture/1st/index.html
Labels: 🔧 리펙토링

#14 [5월] 장준호
  mission/장준호/사전미션.md
  mission/장준호/화면 캡처 2024-05-10 181102.png
Labels: 📚 사전 미션 과제

#24 [5월] 이현걸 / 사전과제 제출
  mission/hyeongirlife/Dockerfile
  mission/hyeongirlife/docker-build-screenshot.png
  mission/hyeongirlife/mission.md
Labels: 📚 사전 미션 과제

#13 [5월] 사전 미션 과제 / 박유진
  mission/yudility/Dockerfile
  mission/yudility/Pre-mission-answer.md
  mission/yudility/docker_build.png
  mission/yudility/docker_run.png
Labels: 📚 사전 미션 과제

#11 pre-mission commit
  mission/groo83/answer.md
Labels: 📚 사전 미션 과제

#2 사전 미션
  mission/스크린샷 2024-05-08 오후 8.52.47.png
  mission/장두혁.md
Labels: 📚 사전 미션 과제

#5 사전과제 제출
  mission/develoHAM/Dockerfile
  mission/develoHAM/hello_world.png
  mission/develoHAM/pre-mission.md
Labels: 📚 사전 미션 과제

#6 사전 과제 제출
  mission/hajinryu/Dockerfile
  mission/hajinryu/img.png
  mission/hajinryu/img_1.png
  mission/hajinryu/img_2.png
  mission/hajinryu/pre-mission.md
Labels: 📚 사전 미션 과제

#7 [5월]사전 미션 과제/손지민
  mission/손지민.md
Labels: 📚 사전 미션 과제

#10 [5월] Docs: 사전미션 과제 완료 / 고낙연
  mission/nakyeonko3/Dockerfile
  mission/nakyeonko3/pre-mission-answer-nak3.md
Labels: 📚 사전 미션 과제, 👏 상세

#28 FIX. cheatsheet
  lecture/1st/cli.md
Labels: 📕 수업 자료 추가/수정

#30 [5월]정현준/ 나만의 도커 컴포즈 파일 콘테스트
  contest/docker-compose/hu6r1s/README.md
  contest/docker-compose/hu6r1s/docker-compose.yml
  contest/docker-compose/hu6r1s/prometheus.yml
Labels: 나만의 도커 컴포즈 파일

#31 [5월]윤채림 / 나만의 도커 컴포즈 파일 콘테스트
  contest/docker-compose/Rachel-3/README.md
  contest/docker-compose/Rachel-3/app/Dockerfile
  contest/docker-compose/Rachel-3/app/app.py
  contest/docker-compose/Rachel-3/app/requirements.txt
  contest/docker-compose/Rachel-3/app/templates/index.html
  contest/docker-compose/Rachel-3/docker-compose-build.png
  contest/docker-compose/Rachel-3/docker-compose-down.png
  contest/docker-compose/Rachel-3/docker-compose.yml
  contest/docker-compose/Rachel-3/to-do-list-1.png
  contest/docker-compose/Rachel-3/to-do-list-2.png
  contest/docker-compose/Rachel-3/to-do-list-3.png
  contest/docker-compose/Rachel-3/to-do-list-4.png
  contest/docker-compose/Rachel-3/to-do-list-5.png
  contest/docker-images/Rachel-3/requirements.txt
  lecture/2nd/dockerfile_example/app.py
Labels: 나만의 도커 컴포즈 파일

#34 lecture_material: Docker CLI 자료 수정
  lecture/1st/cli.md
  mission/스크린샷 2024-05-08 오후 8.52.47.png
Labels: 📕 수업 자료 추가/수정

#32 [5월] 김형진 / 나만의 도커 컴포즈 파일 콘테스트
  contest/docker-compose/jin/README.md
  contest/docker-compose/jin/chat.py
  contest/docker-compose/jin/docker-compose.yaml
  contest/docker-compose/jin/requirements.txt
  contest/docker-compose/jin/utils.py
Labels: 나만의 도커 컴포즈 파일
